Algoritmo "Média das notas"
Var
   nota1, nota2, nota3, nota4, media: real
Inicio
   Escreva("Digite a nota do 1º bimestre: ")
   Leia(nota1)
   Escreva("Digite a nota do 2º bimestre: ")
   Leia(nota2)
   Escreva("Digite a nota do 3º bimestre: ")
   Leia(nota3)
   Escreva("Digite a nota do 4º bimestre: ")
   Leia(nota4)
   media <- (nota1 + nota2 + nota3 + nota4) / 4
   Escreva("A média das notas é: ", media)
Fim
